package Scanner;
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Apr 19 19:28:17 CST 2013
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int In = 49;
  public static final int Class = 39;
  public static final int True = 13;
  public static final int Llave_on = 4;
  public static final int Negacion = 16;
  public static final int MULT = 35;
  public static final int Igual_Comp = 38;
  public static final int If = 23;
  public static final int Llave_off = 3;
  public static final int Void = 32;
  public static final int Static = 20;
  public static final int Igual_Asig = 42;
  public static final int INT = 8;
  public static final int DOTCOMMA = 9;
  public static final int Menor = 43;
  public static final int Else = 31;
  public static final int Extends = 21;
  public static final int Read = 50;
  public static final int Mayor_Igual = 46;
  public static final int AND = 48;
  public static final int Mayor = 45;
  public static final int Corchete_on = 12;
  public static final int OR = 47;
  public static final int Punto = 25;
  public static final int Return = 22;
  public static final int System = 27;
  public static final int While = 26;
  public static final int Menor_Igual = 44;
  public static final int Out = 28;
  public static final int ID = 2;
  public static final int EOF = 0;
  public static final int BOOLEAN = 7;
  public static final int error = 1;
  public static final int COMA = 24;
  public static final int Import = 51;
  public static final int False = 14;
  public static final int Implements = 52;
  public static final int Div = 36;
  public static final int Println = 29;
  public static final int Diferencia = 37;
  public static final int Public = 19;
  public static final int STRING_CONSTANT = 15;
  public static final int PARENT_on = 6;
  public static final int New = 41;
  public static final int Resta = 18;
  public static final int Corchete_off = 11;
  public static final int STRING = 34;
  public static final int Length = 30;
  public static final int Suma = 17;
  public static final int Exit = 53;
  public static final int PARENT_off = 5;
  public static final int Main = 33;
  public static final int This = 40;
  public static final int INTEGER_LITERAL = 10;
  public static final int NUM =54;
}

