
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat May 18 23:45:49 CST 2013
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUMERO = 39;
  public static final int TSTRING = 26;
  public static final int DIFERENCIA = 15;
  public static final int PUNTO_AST = 36;
  public static final int RESTA = 8;
  public static final int INT = 41;
  public static final int PRINTLN = 12;
  public static final int OUT = 47;
  public static final int ASTERISCO = 34;
  public static final int LLAVE_OFF = 14;
  public static final int STATIC = 55;
  public static final int AND = 51;
  public static final int IGUAL = 19;
  public static final int CORCHETE_ON = 20;
  public static final int IN = 33;
  public static final int OR = 32;
  public static final int CLASS = 23;
  public static final int DIV = 28;
  public static final int SUMA = 4;
  public static final int EXIT = 5;
  public static final int IF = 40;
  public static final int PARENT_OFF = 31;
  public static final int MAIN = 7;
  public static final int THIS = 9;
  public static final int PUNTO_COMA = 53;
  public static final int ID = 43;
  public static final int EOF = 0;
  public static final int BOOLEAN = 29;
  public static final int SYSTEM = 37;
  public static final int RETURN = 13;
  public static final int TRUE = 16;
  public static final int PARENT_ON = 10;
  public static final int NEW = 3;
  public static final int error = 1;
  public static final int COMA = 17;
  public static final int NEGACION = 2;
  public static final int MENOR = 11;
  public static final int VOID = 21;
  public static final int MAYOR = 50;
  public static final int IMPORT = 22;
  public static final int TINT = 54;
  public static final int ELSE = 25;
  public static final int CORCHETE_OFF = 42;
  public static final int PUNTO = 38;
  public static final int READ = 27;
  public static final int WHILE = 44;
  public static final int MAYOR_IGUAL = 18;
  public static final int PUBLIC = 30;
  public static final int EXTENDS = 48;
  public static final int IGUAL_COMP = 49;
  public static final int ID2 = 24;
  public static final int LLAVE_ON = 45;
  public static final int STRING = 56;
  public static final int MENOR_IGUAL = 6;
  public static final int FALSE = 52;
  public static final int IMPLEMENTS = 46;
  public static final int LENGTH = 35;
}

